/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.107
 * Generated at: 2025-08-08 02:43:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/navbar.jspf", Long.valueOf(1754621010984L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style>\r\n");
      out.write("	ul {\r\n");
      out.write("	    list-style-type: none;\r\n");
      out.write("	    margin: 0;\r\n");
      out.write("	    padding: 0;\r\n");
      out.write("	    overflow: hidden;\r\n");
      out.write("	    background-color: rgb(53,94,169);\r\n");
      out.write("	    /* background-color:  #999 ; */\r\n");
      out.write("	}\r\n");
      out.write("	li {\r\n");
      out.write("	    float: left;\r\n");
      out.write("	}\r\n");
      out.write("	li a, .dropbtn {\r\n");
      out.write("	    display: inline-block;\r\n");
      out.write("	    color: white;\r\n");
      out.write("	    text-align: center;\r\n");
      out.write("	    padding: 14px 16px;\r\n");
      out.write("	    text-decoration: none;\r\n");
      out.write("	}\r\n");
      out.write("	li a:hover, .dropdown:hover .dropbtn {\r\n");
      out.write("	    /* background-color: red; */\r\n");
      out.write("	    background-color: #6799FF;\r\n");
      out.write("	}\r\n");
      out.write("	li.dropdown {\r\n");
      out.write("	    display: inline-block;\r\n");
      out.write("	}\r\n");
      out.write("	li a.active, a.active:hover{\r\n");
      out.write("	    /* background-color: #4CAF50; */\r\n");
      out.write("	    background-color: #6799FF;\r\n");
      out.write("	}\r\n");
      out.write("	.dropdown-content {\r\n");
      out.write("	    display: none;\r\n");
      out.write("	    position: absolute;\r\n");
      out.write("	    background-color: #f9f9f9;\r\n");
      out.write("	    min-width: 160px;\r\n");
      out.write("	    box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);\r\n");
      out.write("	    z-index: 1;\r\n");
      out.write("	}\r\n");
      out.write("	.dropdown-content a {\r\n");
      out.write("	    color: black;\r\n");
      out.write("	    padding: 12px 16px;\r\n");
      out.write("	    text-decoration: none;\r\n");
      out.write("	    display: block;\r\n");
      out.write("	    text-align: left;\r\n");
      out.write("	}\r\n");
      out.write("	.dropdown-content a:hover {background-color: #f1f1f1}\r\n");
      out.write("	.dropdown:hover .dropdown-content {\r\n");
      out.write("	    display: block;\r\n");
      out.write("	}\r\n");
      out.write("	  table     { width:680px; text-align:center; }\r\n");
      out.write("        th        { background-color:cyan; }\r\n");
      out.write("        \r\n");
      out.write("        .num      { width: 80px; }\r\n");
      out.write("        .title    { width:230px; }\r\n");
      out.write("        .writer   { width:100px; }\r\n");
      out.write("        .regtime  { width:180px; }\r\n");
      out.write("                \r\n");
      out.write("        a:link    { text-decoration:none;  }\r\n");
      out.write("        a:visited { text-decoration:none;  }\r\n");
      out.write("        a:hover   { text-decoration:none;   }\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<ul>\r\n");
      out.write("		  <li><a href=\"#home\">Home</a></li>\r\n");
      out.write("		  <li><a href=\"boardList.jsp\">게시판</a></li>\r\n");
      out.write("		  <li><a href=\"#cafe\">카페</a></li>\r\n");
      out.write("		  <li><a href=\"#blog\">블로그</a></li>\r\n");
      out.write("		  <li class=\"dropdown\">\r\n");
      out.write("			    <a href=\"#shopping\" class=\"dropbtn\">쇼핑</a>\r\n");
      out.write("			    <div class=\"dropdown-content\">\r\n");
      out.write("				      <a href=\"#\">가전제품</a>\r\n");
      out.write("				      <a href=\"#\">의류/악세사리</a>\r\n");
      out.write("				      <a href=\"#\">가방/신발</a>\r\n");
      out.write("			    </div>\r\n");
      out.write("		  </li>\r\n");
      out.write("		  <li class=\"dropdown\">\r\n");
      out.write("			    <a href=\"#new\" class=\"dropbtn\">뉴스</a>\r\n");
      out.write("			    <div class=\"dropdown-content\">\r\n");
      out.write("			      <a href=\"#\">정치</a>\r\n");
      out.write("				      <a href=\"#\">경제</a>\r\n");
      out.write("				      <a href=\"#\">생활/문화</a>\r\n");
      out.write("			    </div>\r\n");
      out.write("		  </li>\r\n");
      out.write("		  <li style=\"float:right\"><a class=\"active\" href=\"#login\">로그인</a></li>\r\n");
      out.write("	</ul>\r\n");
      out.write("\r\n");
      out.write("<h1>홈페이지</h1>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
